const colors = {
  zinc: {
    night: {
      bg: "bg-zinc-800",
      codeBg: "bg-zinc-600",
      text: "text-zinc-100",
      textHover: "hover:text-zinc-400",
      textActive: "active:text-zinc-500",
      subText: "text-zinc-400",
      subTextHover: "hover:text-zinc-300",
      subTextSelected: "text-zinc-300",
      icon: "text-zinc-500",
      iconSelected: "text-zinc-200",
      iconHover: "hover:text-zinc-200",
      lightModeHover: "hover:text-yellow-300",
      svg: "fill-zinc-100",
      svgHover: "hover:fill-zinc-400",
    },
    day: {
      bg: "bg-zinc-50",
      codeBg: "bg-zinc-300",
      text: "text-zinc-950",
      textHover: "hover:text-zinc-500",
      textActive: "active:text-zinc-400",
      subText: "text-zinc-600",
      subTextHover: "hover:text-zinc-900",
      subTextSelected: "text-zinc-900",
      icon: "text-zinc-400",
      iconSelected: "text-zinc-900",
      iconHover: "hover:text-zinc-900",
      lightModeHover: "hover:text-yellow-400",
      svg: "fill-zinc-800",
      svgHover: "hover:fill-zinc-600",
    },
  },
  slate: {
    night: {
      bg: "bg-slate-800",
      codeBg: "bg-slate-600",
      text: "text-slate-100",
      textHover: "hover:text-slate-400",
      textActive: "active:text-slate-500",
      subText: "text-slate-400",
      subTextHover: "hover:text-slate-300",
      subTextSelected: "text-slate-300",
      icon: "text-slate-500",
      iconSelected: "text-slate-200",
      iconHover: "hover:text-slate-200",
      lightModeHover: "hover:text-yellow-300",
      svg: "fill-slate-100",
      svgHover: "hover:fill-slate-400",
    },
    day: {
      bg: "bg-slate-50",
      codeBg: "bg-slate-300",
      text: "text-slate-950",
      textHover: "hover:text-slate-500",
      textActive: "active:text-slate-400",
      subText: "text-slate-600",
      subTextHover: "hover:text-slate-900",
      subTextSelected: "text-slate-900",
      icon: "text-slate-400",
      iconSelected: "text-slate-900",
      iconHover: "hover:text-slate-900",
      lightModeHover: "hover:text-yellow-400",
      svg: "fill-slate-800",
      svgHover: "hover:fill-slate-600",
    },
  },
  stone: {
    night: {
      bg: "bg-stone-800",
      codeBg: "bg-stone-600",
      text: "text-stone-100",
      textHover: "hover:text-stone-400",
      textActive: "active:text-stone-500",
      subText: "text-stone-400",
      subTextHover: "hover:text-stone-300",
      subTextSelected: "text-stone-300",
      icon: "text-stone-500",
      iconSelected: "text-stone-200",
      iconHover: "hover:text-stone-200",
      lightModeHover: "hover:text-yellow-300",
      svg: "fill-stone-100",
      svgHover: "hover:fill-stone-400",
    },
    day: {
      bg: "bg-stone-50",
      codeBg: "bg-stone-300",
      text: "text-stone-950",
      textHover: "hover:text-stone-500",
      textActive: "active:text-stone-400",
      subText: "text-stone-600",
      subTextHover: "hover:text-stone-900",
      subTextSelected: "text-stone-900",
      icon: "text-stone-400",
      iconSelected: "text-stone-900",
      iconHover: "hover:text-stone-900",
      lightModeHover: "hover:text-yellow-400",
      svg: "fill-stone-800",
      svgHover: "hover:fill-stone-600",
    },
  },
  gray: {
    night: {
      bg: "bg-gray-800",
      codeBg: "bg-gray-600",
      text: "text-gray-100",
      textHover: "hover:text-gray-400",
      textActive: "active:text-gray-500",
      subText: "text-gray-400",
      subTextHover: "hover:text-gray-300",
      subTextSelected: "text-gray-300",
      icon: "text-gray-500",
      iconSelected: "text-gray-200",
      iconHover: "hover:text-gray-200",
      lightModeHover: "hover:text-yellow-300",
      svg: "fill-gray-100",
      svgHover: "hover:fill-gray-400",
    },
    day: {
      bg: "bg-gray-50",
      codeBg: "bg-gray-300",
      text: "text-gray-950",
      textHover: "hover:text-gray-500",
      textActive: "active:text-gray-400",
      subText: "text-gray-600",
      subTextHover: "hover:text-gray-900",
      subTextSelected: "text-gray-900",
      icon: "text-gray-400",
      iconSelected: "text-gray-900",
      iconHover: "hover:text-gray-900",
      lightModeHover: "hover:text-yellow-400",
      svg: "fill-gray-800",
      svgHover: "hover:fill-gray-600",
    },
  },
};

export { colors };
